### ISSUE TITLE
Request: Support more than one docs plugin

### ISSUE THREAD

**Issue by 0xGizmo** [cmfcmf/docusaurus-search-local#70] opened 2021-11-07 05:49 UTC
I am building a docs site and we have three instances of `@docusaurus/plugin-content-docs`. Each have their own unique ID.

Unfortuantely `docusuaurus-search-local` doesn't support multiple `plugin-content-docs` instances and enforces indexing of the `default` ID.

Please add support for multiple instances of `plugin-content-docs`.

**Comment by cmfcmf** [comment] 2021-12-03 17:48
Closing as a duplicate of #33.

**Closed by cmfcmf** 2021-12-03 17:48 UTC
Labels: enhancement

**Comment by cmfcmf** [comment] 2021-12-04 22:54
Implemented in 0.8.0.
