### ISSUE TITLE
An error occurred when clicking on the result

### ISSUE THREAD

**Issue by Chasen-Zhang** [cmfcmf/docusaurus-search-local#143] opened 2022-09-22 14:30 UTC
### Please describe the bug you are seeing

![image](https://user-images.githubusercontent.com/15354455/191774486-be3f317f-cfdb-43a2-a1fa-ddb790af0dea.png)

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

"@cmfcmf/docusaurus-search-local": "^0.11.0",

### Which Node.js version are you using?

v16.17.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

![image](https://user-images.githubusercontent.com/15354455/191774844-834686c9-3f5b-49af-96c9-879d8288be88.png)

**Comment by cmfcmf** [comment] 2023-02-25 20:39
I am afraid that I cannot reproduce this error, thus closing for now.

**Closed by cmfcmf** 2023-02-25 20:39 UTC
Labels: bug
