### ISSUE TITLE
This plug-in conflict with `i18n`

### ISSUE THREAD

**Issue by geometryolife** [cmfcmf/docusaurus-search-local#129] opened 2022-08-03 07:30 UTC
### Please describe the bug you are seeing

![93DB0BEC-80D8-49E5-B866-17DF7F28661A](https://user-images.githubusercontent.com/54882546/182548563-0b493ec6-f079-4128-a0c4-0a34b9e4032c.jpeg)

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

![0FE7D03C-4FAF-4C8B-90A6-DF54548F242E](https://user-images.githubusercontent.com/54882546/182549013-311e45b0-bca1-4a18-9ccf-cf1760fcc5f3.jpeg)

### Which Node.js version are you using?

v16.16.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

My configuration is [here](https://github.com/starcoinorg/starcoin-cookbook/blob/main/docusaurus.config.js)

**Comment by juansalvatore** [comment] 2023-02-02 02:26
any news on how we can fix this issue?

**Comment by cmfcmf** [comment] 2023-02-25 10:47
Closing as a duplicate of #163.

**Closed by cmfcmf** 2023-02-25 10:47 UTC
Labels: bug
